### PR TITLE
fix: links in ADOPTERS

### PR DESCRIPTION
**Pull request by jonas-jonas**
Links in ADOPTERS.md still point to the fork. This fixes that. :)

### CODE REVIEW

**Review by vinckr — APPROVED** [review]
Thanks :)

**Review by kevgo — APPROVED** [review]
Thanks for fixing this!

**Comment by vinckr** [comment]
Whats with the "Semantic Pull Request" and "check format" checks? seems stuck...

**Comment by jonas-jonas** [comment]
I restarted the checks, lets see^^

**Comment by kevgo** [comment]
> Whats with the "Semantic Pull Request" and "check format" checks? seems stuck...

These are old checks that no longer work. I'll remove them once I get the admin rights to do so.

**Pull request merged**
