### PR TITLE
feat: add text-run and fix problems found by it

### PR DESCRIPTION
**Pull request by zepatrik**
Note that there are some problems that are caused due to templating. Because of that, I did not add it to the CI yet. See https://github.com/kevgo/text-runner/issues/1401 for more info.

### CODE REVIEW

**Comment by vinckr** [comment]
Found one

https://github.com/ory/meta/pull/90

**Comment by zepatrik** [comment]
The CI fails where the reason for this PR in the first place :wink:

**Comment by aeneasr** [comment]
please resolve merge conflict

**Comment by aeneasr** [comment]
@zepatrik bringing this in your inbox

**Comment by zepatrik** [comment]
done

**Pull request merged**
