### PR TITLE
Dark theme support

### PR DESCRIPTION
**Pull request by jonas-jonas**
Preview is here: https://github.com/jonas-jonas/meta/blob/dark-theme-support/templates/repository/common/ADOPTERS.md

This PR changes the images/logos of our adopters to be readable in dark theme and light theme.

Most of the logos were black so the "dark theme version" is now just the inverted color (mostly white).
Unfortunately, some had a different color and I did not want to change their brand colors to something else. The result is that a few of the logos look out of place because they're quite dark and not really readable, while the others are white.

Example:
image

### CODE REVIEW

**Comment by jonas-jonas** [comment]
cc @vinckr 

IMPORTANT: Before merging this, we need to update the links as they point to my fork and the feature branch. I will do this, once we have approval :)

**Comment by vinckr** [comment]
Awesome 🎉 

was Buhta the only logo that is not in black? They all should be black/white anyway, so no brand colours! 

If possible could you change the non-black logos to black as well? 🙏

**Comment by jonas-jonas** [comment]
I update TierIV & Buhta. 
I did not get Ordermygear and R2Devops to work, maybe @jfcurran can help out here.

**Comment by vinckr** [comment]
I will reach out to Ordermygear and R2Devops if they can supply us a white version of their logo. That would be enough right?

**Comment by jonas-jonas** [comment]
@vinckr yes, that should be fine!

**Pull request merged**
