### PR TITLE
docs: add adopter

### PR DESCRIPTION
**Pull request by vinckr**
Screenshot 2022-09-05 at 15 37 19

### CODE REVIEW

**Comment by aeneasr** [comment]
pls also add luna sec :)

**Comment by vinckr** [comment]
Screenshot 2022-09-05 at 16 57 14

**Comment by aeneasr** [comment]
can you add luna also to the website?

**Comment by vinckr** [comment]
> can you add luna also to the website?

sure, but in a different PR 😅

**Pull request merged**
