### PR TITLE
fix: Allow empty commits + CI checks

### PR DESCRIPTION
**Pull request by kevgo**
Multiple changes in one PR to eliminate review latency:

- feat: adds the ability to test committing locally and allows that repos have no commits
- chore: rename `$push` to `$persist`
- ci: test-drive a sync on CI before merging and running the sync for real

### CODE REVIEW

**Comment by kevgo** [comment]
@aeneasr can you please set up the SSH key for this CI job similar to the setup of `test.yml`? This is needed to clone private repos and dry-run the sync. It doesn't push changes back into repos since it is a dry run.

**Comment by aeneasr** [comment]
Not sure if I follow? I think you just need to use the `SSH_PRIVATE_KEY` secret!

**Comment by kevgo** [comment]
Yes, I need the `SSH_PRIVATE_KEY` secret set for the `test` job. It isn't set right now, see the failing test below. I assume you have to configure it somewhere? It is set for the `sync` job.

If you think it is set for this job, it might be because this PR comes from a fork, and sometimes those PRs don't see secrets when they run.

image

**Comment by kevgo** [comment]
@aeneasr can you please take a look at the error I screenshotted above and set up the secrets so that the `webfactory/ssh-agent` step passes for `.github/workflows/test.yml` the same way it does for `.github/workflows/sync.yml`?

**Comment by kevgo** [comment]
The [webfactory/ssh-agent](https://github.com/kevgo-ory/meta/blob/kg-allow-empty-commits/.github/workflows/test.yml#L14-L16) step is failing because `secrets.SSH_PRIVATE_KEY` is not set for the [test job](https://github.com/kevgo-ory/meta/blob/kg-allow-empty-commits/.github/workflows/test.yml).

**Comment by kevgo** [comment]
Closing in favor of https://github.com/ory/meta/pull/170.

**Pull request closed without merging**
